branches:
  only:
    - master

configuration: Release

build_script:
  - cmd: dotnet build src/CodeAnalyzers.Episerver/CodeAnalyzers.Episerver.csproj


test_script:
  - cmd: dotnet test test/CodeAnalyzers.Episerver.Test/CodeAnalyzers.Episerver.Test.csproj