trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: dotnet build --configuration Release src/CodeAnalyzers.Episerver/CodeAnalyzers.Episerver.csproj

- script: dotnet test test/CodeAnalyzers.Episerver.Test/CodeAnalyzers.Episerver.Test.csproj

- task: CopyFiles@2
  displayName: 'Copy package'
  inputs:
    Contents: '**/Release/**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    FlattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Pubslih artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'