trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: 'src/CodeAnalyzers.Episerver/CodeAnalyzers.Episerver.csproj'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test $(BuildConfiguration)'
  inputs:
    command: 'test'
    projects: 'test/**/*.csproj'
    configuration: '$(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Pack $(BuildConfiguration)'
  inputs:
    command: 'pack'
    packagesToPack: 'src/CodeAnalyzers.Episerver/CodeAnalyzers.Episerver.csproj'
    versioningScheme: 'off'
    configuration: '$(BuildConfiguration)'