trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  displayName: 'Integration test'
  inputs:
    solution: 'integration\CodeAnalyzers.Episerver.Integration\CodeAnalyzers.Episerver.Integration.sln'
    configuration: $(buildConfiguration)
    clean: true
